services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: product-app
    command: ["java", "-jar", "app.jar", "--spring.data.mongodb.uri=mongodb://mongodb:27017/product_db"]
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/product_db

volumes:
  mongo-data:
