spring.application.name=product-app
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.orm.jpa.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.mongo.autoconfigure.MongoAutoConfiguration,org.springframework.boot.data.mongo.autoconfigure.MongoDataAutoConfiguration
app.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/product_db}
